imports:
  - { resource: config.yml }

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    # El handler 'main' ahora escribe a la salida estándar de Docker
    main:
      type: stream
      # Ruta especial que apunta a la salida estándar
      path: "php://stdout"
      # Capturamos todos los logs desde el nivel 'debug'
      level: debug
      # Usamos el formateador JSON para que la salida sea estructurada
      # Esto es lo que Promtail leerá
      formatter: monolog.formatter.json
    # Mantenemos el handler de la consola para los comandos de consola
    console:
      type: console
      channels: ["!event", "!doctrine", "!security"]
